return {
  'chentoast/marks.nvim',
  event = "VeryLazy",
  cond = not vim.g.vscode,
  opts = {
    default_mappings = true,
    cyclic = true,
    force_write_shada = false,
    refresh_interval = 250,
    sign_priority = { lower = 10, upper = 15, builtin = 8, bookmark = 20 },
    excluded_filetypes = { "", "fzf" },
    bookmark_0 = { sign = "0" },
    bookmark_1 = { sign = "1" },
    bookmark_2 = { sign = "2" },
    bookmark_3 = { sign = "3" },
    bookmark_4 = { sign = "4" },
    bookmark_5 = { sign = "5" },
    bookmark_6 = { sign = "6" },
    bookmark_7 = { sign = "7" },
    bookmark_8 = { sign = "8" },
    bookmark_9 = { sign = "9" },
  },
}
